dataset: MNIST
device: [0]

ipc: 10
syn_steps: 80
expert_epochs: 2
zca: False
lr_img: 1
lr_teacher: 0.01
buffer_path: ../buffer_storage/
data_path: ../dataset
ema_decay: 0.9995
Iteration: 10
batch_syn: 100

# wandb
project: MNIST_ipc10

num_eval: 1
eval_it: 10
skip_first_eva: True

lr_y: 1.0
Momentum_y: 0.9
threshold: 1.
pix_init: samples_predicted_correctly
batch_train: 128

min_start_epoch: 0
current_max_start_epoch: 1
max_start_epoch: 2
# loss_threshold_low: 1.0

lr_lr: 0.00001
zca: True

depth_ratio: 0.5
loss_ratio: 0.5